### PR TITLE
Use with Angular 4

### PR DESCRIPTION
**Pull request by yoosif0**

### CODE REVIEW

**Comment by 02harleen** [comment]
How to update ngx-rating files.

**Comment by sanjaykumar2338** [comment]
Hi,

import { RatingModule } from 'ngx-bootstrap/rating';

<rating  formControlName="review_rating" [float]="true"  class="rating rating-stars"></rating>

Can't bind to 'float' since it isn't a known property of 'rating'. ("Your_Rating')}}</label>
								<div>												
									<rating  formControlName="review_rating" [ERROR ->][float]="true"  class="rating rating-stars"></rating>
									<!--<div class="rating-stars">
							"): WriteReview@184:50 ; Zone: <root> ; Task: Promise.then ; Value:


Please help.

**Comment by Vadorequest** [comment]
@pleerock You haven't opened the issues for this repo.

I'm a beginner with Angular io (2-4), I don't understand the following part:

  ```
<md-list
    dense
  >
    <md-list-item
      *ngFor="let movie of movies"
      [class.selected]="movie === selectedMovie"
      (click)="onSelect(movie)"
    >
      {{movie.title}}
      <rating
        [(ngModel)]="movie.vote_average" <-- this line fails with "Can't bind to "ngModel" since it isn't a known property of 'rating'". 
        [readonly]="true"
        [max]="10"
        [float]="true"
      >
      </rating>
    </md-list-item>
  </md-list>
```

I was wondering if I could just provide some kind of value, since I use it in a read-only mode, I don't need to bind it to a model since it won't change. Also, I don't understand how to do it properly with a model since I'm manipulating a list. I saw you used an array in an example, but it's kinda an ugly duplicate in my case...
If you have any advice, thanks!

**Comment by pleerock** [comment]
There is no issues and accepting PRs because this repo is not maintaining (see no in the readme). Consider making your own fork.

**Pull request closed without merging**
